import { FeatureDependency } from "../visualizer";

export interface IsolationRule {
  feature: string;
  forbidden: string[];
  reason?: string;
}

export interface GuardViolation {
  from: string;
  to: string;
  files: string[];
  rule: IsolationRule;
}

/**
 * Guard: Enforces architectural boundary rules.
 * Prevents domain leaks and unintended coupling.
 */
export class Guard {
  private config: IsolationRule[];

  constructor(rules: IsolationRule[]) {
    this.config = rules;
  }

  /**
   * Checks for rule violations against detected dependencies.
   */
  public check(deps: FeatureDependency[]): GuardViolation[] {
    const violations: GuardViolation[] = [];

    for (const rule of this.config) {
      // Find dependencies that originate from the restricted feature
      const relevantDeps = deps.filter((d) => d.from === rule.feature);

      for (const dep of relevantDeps) {
        if (rule.forbidden.includes(dep.to) || rule.forbidden.includes("*")) {
          // If the target is forbidden (or everything is forbidden except shared/lib)
          violations.push({
            from: dep.from,
            to: dep.to,
            files: dep.files,
            rule: rule,
          });
        }
      }
    }

    return violations;
  }

  public generateReport(violations: GuardViolation[]): string {
    if (violations.length === 0) {
      return `# 🛡️ Architecture Guard: PASS\n\n✅ No domain-isolation violations detected. All features are respecting designated boundaries.`;
    }

    let md = `# 🛡️ Architecture Guard: FAIL\n\n`;
    md += `🔴 **${violations.length} violations detected.** These imports breach our domain-isolation standards.\n\n`;

    md += `## 🚩 Violations\n\n`;
    violations.forEach((v) => {
      md += `### ${v.from} ➔ ${v.to}\n`;
      md += `**Rule**: \`${v.from}\` is forbidden from importing \`${v.to}\`\n`;
      if (v.rule.reason) md += `**Reason**: ${v.rule.reason}\n`;
      md += `**Files**:\n`;
      v.files.forEach((f) => (md += `- \`${f}\`\n`));
      md += `\n`;
    });

    md += `\n---\n*Generated by Questerix Cortex Guard*`;
    return md;
  }
}
