import React, { useState } from 'react';
import Papa from 'papaparse';
import { useBulkImport, QueuedQuestion } from '@/hooks/useBulkImport';
import { useSkills } from '@/features/curriculum/hooks/use-skills';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Upload, FileText, CheckCircle2 } from 'lucide-react';
import { toast } from '@/hooks/use-toast';
import { AdminHeader } from '@/components/ui/admin-header';

export const BulkImportPage = () => {
  const [file, setFile] = useState<File | null>(null);
  const [parsedData, setParsedData] = useState<QueuedQuestion[]>([]);
  const [selectedSkillId, setSelectedSkillId] = useState<string>('');
  const { importQuestions, importing } = useBulkImport();
  const { data: skills } = useSkills();

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setFile(file);

    Papa.parse(file, {
      header: true,
      skipEmptyLines: true,
      complete: (results) => {
        try {
            // Map CSV fields to QueuedQuestion
            const mappedData: QueuedQuestion[] = results.data.map((row: any) => ({
              skill_id: selectedSkillId, // Will be overridden on submit
              content: row.content,
              type: (row.type as any) || 'multiple_choice',
              points: parseInt(row.points) || 1,
              is_published: false,
              explanation: row.explanation,
              // Handle JSON fields safely
              options: row.options ? (typeof row.options === 'string' ? JSON.parse(row.options) : row.options) : {},
              solution: row.solution ? (typeof row.solution === 'string' ? JSON.parse(row.solution) : row.solution) : {},
            })).filter((q: QueuedQuestion) => q.content && q.solution);

            setParsedData(mappedData);
            toast({
                title: "File Parsed Successfully",
                description: `Found ${mappedData.length} valid questions.`,
            });
        } catch (err: any) {
            console.error(err);
            toast({
                title: "Parsing Error",
                description: "Failed to parse CSV JSON fields. Ensure options/solution are valid JSON.",
                variant: "destructive"
            });
            setParsedData([]);
        }
      },
      error: (error) => {
        toast({
            title: "CSV Error",
            description: error.message,
            variant: "destructive"
        });
      }
    });
  };

  const handleSubmit = async () => {
    if (!selectedSkillId) {
       toast({
           title: "Missing Skill",
           description: "Please select a target skill first.",
           variant: "destructive"
       });
       return;
    }
    
    // Assign selected skill to all questions
    const finalData = parsedData.map(q => ({ ...q, skill_id: selectedSkillId }));
    
    const success = await importQuestions(finalData);
    if (success) {
        setParsedData([]);
        setFile(null);
        // Reset file input
        const input = document.getElementById('csv-upload') as HTMLInputElement;
        if (input) input.value = '';
    }
  };

  return (
    <div className="space-y-8">
      <AdminHeader 
        title="Bulk Import Questions" 
        description="Import questions from CSV files generated by the AI Content tool or created manually."
        icon={Upload}
      />

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <Card className="border-blue-100 shadow-sm">
            <CardHeader>
                <CardTitle className="text-blue-900">1. Select Target Skill</CardTitle>
                <CardDescription>All imported questions will be added to this skill.</CardDescription>
            </CardHeader>
            <CardContent>
                <Select value={selectedSkillId} onValueChange={setSelectedSkillId}>
                    <SelectTrigger className="w-full">
                        <SelectValue placeholder="Select a skill..." />
                    </SelectTrigger>
                    <SelectContent>
                        {skills?.map(skill => (
                            <SelectItem key={skill.skill_id} value={skill.skill_id}>
                                {skill.title}
                            </SelectItem>
                        ))}
                    </SelectContent>
                </Select>
            </CardContent>
          </Card>

          <Card className="border-purple-100 shadow-sm">
            <CardHeader>
                <CardTitle className="text-purple-900">2. Upload CSV</CardTitle>
                <CardDescription>File must contain: content, type, points, solution (JSON), options (JSON).</CardDescription>
            </CardHeader>
            <CardContent>
                <div className="border-2 border-dashed border-gray-300 rounded-lg p-8 text-center hover:border-purple-500 transition-colors bg-gray-50">
                    <Input 
                        type="file" 
                        accept=".csv" 
                        onChange={handleFileUpload} 
                        className="hidden" 
                        id="csv-upload" 
                    />
                    <label htmlFor="csv-upload" className="cursor-pointer flex flex-col items-center gap-2 w-full h-full justify-center">
                        <Upload className="w-10 h-10 text-gray-400" />
                        <span className="text-sm font-medium text-gray-600">Click to upload CSV</span>
                    </label>
                </div>
                {file && (
                    <div className="mt-4 flex items-center gap-2 text-sm text-green-600 bg-green-50 p-2 rounded border border-green-100">
                        <FileText className="w-4 h-4" />
                        <span className="font-semibold">{file.name}</span>
                        <span className="text-gray-500">({parsedData.length} valid rows)</span>
                    </div>
                )}
            </CardContent>
          </Card>
      </div>

      {parsedData.length > 0 && selectedSkillId && (
         <div className="flex justify-end animate-in fade-in slide-in-from-bottom-4">
             <Button 
                onClick={handleSubmit} 
                disabled={importing} 
                size="lg"
                className="bg-green-600 hover:bg-green-700 min-w-[200px]"
             >
                {importing ? (
                    <span className="flex items-center gap-2">
                        <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                        Importing...
                    </span>
                ) : (
                    <span className="flex items-center gap-2">
                        <CheckCircle2 className="w-4 h-4" />
                        Confirm Import ({parsedData.length})
                    </span>
                )}
             </Button>
         </div>
      )}

      {/* Preview Grid (Optional, simple list for now) */}
      {parsedData.length > 0 && (
        <Card>
            <CardHeader>
                <CardTitle>Preview</CardTitle>
            </CardHeader>
            <CardContent>
                <div className="max-h-[400px] overflow-y-auto border rounded-md">
                    <table className="w-full text-sm text-left">
                        <thead className="bg-gray-50 sticky top-0">
                            <tr>
                                <th className="p-2 border-b">#</th>
                                <th className="p-2 border-b">Content</th>
                                <th className="p-2 border-b">Type</th>
                                <th className="p-2 border-b">Points</th>
                            </tr>
                        </thead>
                        <tbody>
                            {parsedData.map((q, i) => (
                                <tr key={i} className="border-b hover:bg-gray-50">
                                    <td className="p-2">{i + 1}</td>
                                    <td className="p-2 truncate max-w-xs" title={q.content}>{q.content}</td>
                                    <td className="p-2">{q.type}</td>
                                    <td className="p-2">{q.points}</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </CardContent>
        </Card>
      )}
    </div>
  );
};
