import { defineConfig, devices } from '@playwright/test';
import * as dotenv from 'dotenv';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load test environment variables
dotenv.config({ path: path.resolve(__dirname, '.env.test.local') });
dotenv.config({ path: path.resolve(__dirname, '.env.test') });

// Pre-authenticated storageState paths — generated by tests/global-setup.ts
// ⚠️  .auth/ is gitignored — never commit session cookies.
const AUTH_DIR = path.resolve(__dirname, '.auth');
const authState = (role: string) => path.join(AUTH_DIR, `${role}.json`);

export default defineConfig({
  testDir: './tests',
  globalSetup: './tests/global-setup.ts',
  fullyParallel: true,
  forbidOnly: Boolean(process.env.CI),
  retries: process.env.CI ? 2 : 0,
  workers: 1, // Set to 1 to avoid race conditions during seeding in local/cloud DB
  timeout: 60000, // 60 seconds per test
  expect: {
    timeout: 10000, // 10 seconds for assertions
    toHaveScreenshot: {
      maxDiffPixelRatio: 0.05, // Allow 5% pixel difference for rendering noise
    },
  },
  snapshotPathTemplate: '{testDir}/__screenshots__/{projectName}/{testFilePath}/{arg}{ext}',
  reporter: [
    ['html', { open: 'never' }],
    ['list'],
    ['json', { outputFile: 'test-results/results.json' }],
  ],
  use: {
    baseURL: 'http://localhost:5000',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    actionTimeout: 15000,
  },
  projects: [
    // ── Authenticated projects (use SUPER_ADMIN storageState by default) ──────
    // Tests that need a different role must call test.use({ storageState: authState('admin') })
    {
      name: 'desktop',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1440, height: 900 },
        storageState: authState('super-admin'),
      },
    },
    {
      name: 'mobile',
      use: {
        ...devices['iPhone 12'],
        viewport: { width: 375, height: 812 },
        storageState: authState('super-admin'),
      },
    },
    {
      name: 'tablet',
      use: {
        ...devices['iPad Mini'],
        viewport: { width: 768, height: 1024 },
        storageState: authState('super-admin'),
      },
    },

    // ── Unauthenticated project ────────────────────────────────────────────────
    // For tests that explicitly test unauthenticated flows:
    //   auth-flow.e2e.spec.ts, auth-registration.e2e.spec.ts,
    //   rbac-guards (RBAC-003, MENTOR-006)
    // These tests must also set: test.use({ storageState: { cookies: [], origins: [] } })
    {
      name: 'unauthenticated',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1440, height: 900 },
        storageState: { cookies: [], origins: [] },
      },
    },
  ],
  webServer: {
    command: 'npm run dev -- --mode test',
    url: 'http://localhost:5000',
    reuseExistingServer: !process.env.CI,
    timeout: 120000, // 2 minutes to start server
  },
});
