import Database from "better-sqlite3";
import { execSync } from "child_process";
import * as fs from "fs";
import * as path from "path";
import { checkCompliance } from "../mcp-server/compliance";
import { TaskResult } from "../orchestrator";
import type { CortexConfig } from "../types";

// Helper interfaces for graph queries
interface RiskyFile {
  file_path: string;
  fanin: number;
  fragility_index: number | null;
}

interface FeatureHealth {
  feature: string;
  verdict: string;
  coverage: number;
  coupling: number;
}

interface SessionSummary {
  session_id: string;
  tool_calls: string[];
  files_changed: number;
  timestamp: string;
}

export class Reporter {
  private outputs: any;
  private root: string;
  private projectRoot: string;

  constructor(root: string, outputs: any, projectRoot?: string) {
    this.root = root;
    this.outputs = outputs;
    this.projectRoot = projectRoot || path.resolve(root, "..");
  }

  generate(
    results: Record<string, TaskResult>,
    surfaceMap?: any,
    analystResults?: any,
    driftResult?: any,
    rlsResult?: any,
    history?: any[],
    governanceResult?: {
      deadRefs: Array<{ file: string; ref: string }>;
      scannedFiles: number;
    },
    optimizeResult?: any,
    deltaResult?: any,
    riskScore?: any,
  ) {
    this.generateHealthReport(
      results,
      analystResults,
      surfaceMap,
      rlsResult,
      governanceResult,
    );
    if (optimizeResult) {
      this.generateOptimizeReport(optimizeResult);
    }
    this.generateAgentContext(
      results,
      surfaceMap,
      analystResults,
      driftResult,
      rlsResult,
      history,
    );
    this.generateNextTask(results, analystResults, surfaceMap);
    // generateMachineBriefing removed - content merged into AGENT_CONTEXT.md
    this.generateFailureDigest(results);
    this.generateLastChanged();
    this.autoAppendLearning(results);

    // Track C: Nightly Failure Reporting
    if (process.env.CORTEX_GHA === "true") {
      this.dispatchGithubIssues(results);
    }
  }

  /**
   * Automatically creates GitHub issues for failed suites using the 'gh' CLI.
   * Only active in CI environments (CORTEX_GHA=true).
   */
  private dispatchGithubIssues(results: Record<string, TaskResult>): void {
    const failures = Object.values(results).filter(
      (r) => r.status === "failed",
    );
    if (failures.length === 0) return;

    console.log(
      `\n📢 Dispatching ${failures.length} failure(s) to GitHub Issues...`,
    );

    for (const f of failures) {
      const title = `🚨 Nightly Failure: ${f.name}`;
      const firstError = this.extractFirstError(f.output);
      const body =
        `### Suite: ${f.name}\n` +
        `**Status**: FAILED\n` +
        `**Duration**: ${f.duration?.toFixed(1) ?? "?"}s\n` +
        `**First Error**: \`${firstError}\`\n\n` +
        `#### Failure Digest\n` +
        `\`\`\`\n${f.output?.slice(-1500) ?? "No output captured."}\n\`\`\`\n\n` +
        `*Generated by Questerix Cortex*`;

      try {
        // Use gh CLI to check for existing open issues with same title to avoid duplicates
        const existing = this.safeExec(
          `gh issue list --search "${title}" --state open --json number --limit 1`,
          this.projectRoot,
        );
        const hasExisting = existing && JSON.parse(existing).length > 0;

        if (!hasExisting) {
          this.safeExec(
            `gh issue create --title "${title}" --body "${body.replace(/"/g, '\\"')}" --label "nightly-regression,automated"`,
            this.projectRoot,
          );
          console.log(`   ✅ Created issue for ${f.name}`);
        } else {
          console.log(`   ⏭️ Skipping ${f.name} (open issue already exists)`);
        }
      } catch (err) {
        console.error(`   ❌ Failed to dispatch issue for ${f.name}:`, err);
      }
    }
  }

  // ─────────────────────────────────────────────────────────────
  // HEALTH REPORT
  // ─────────────────────────────────────────────────────────────
  private generateHealthReport(
    results: Record<string, TaskResult>,
    analystResults?: any,
    surfaceMap?: any,
    rlsResult?: any,
    governanceResult?: {
      deadRefs: Array<{ file: string; ref: string }>;
      scannedFiles: number;
    },
  ) {
    let md = "# 🩺 Questerix Health Report\n\n";
    md += `*Generated: ${new Date().toLocaleString()}*\n\n`;

    const allResults = Object.values(results);
    const passed = allResults.filter((r) => r.status === "passed").length;
    const total = allResults.length;
    const score = total > 0 ? Math.round((passed / total) * 100) : 0;

    md += `## Overall Health Score: ${score}/100\n\n`;
    md += "| Suite | Status | Duration |\n";
    md += "| :--- | :--- | :--- |\n";

    for (const r of allResults) {
      const icon = r.status === "passed" ? "✅" : "❌";
      md += `| ${r.name} | ${icon} ${r.status.toUpperCase()} | ${r.duration?.toFixed(1) || 0}s |\n`;
    }

    if (analystResults?.bundleSize) {
      md += `\n**Production Bundle**: ${analystResults.bundleSize} KB\n`;
    }

    if (analystResults?.deadCode?.length > 0) {
      md += "\n## 🕵️ Analyst Findings\n";
      md += `**Dead Code**: ${analystResults.deadCode.length} unused exports.\n`;
    }

    if (analystResults?.perfGaps?.length > 0) {
      md += "\n## ⚡ Performance Audit\n";
      md += `**Uninstrumented hooks**: ${analystResults.perfGaps.length} missing \`performance.mark\`\n`;
      analystResults.perfGaps
        .slice(0, 10)
        .forEach((g: string) => (md += `- [ ] \`${g}\`\n`));
      if (analystResults.perfGaps.length > 10)
        md += `*... and ${analystResults.perfGaps.length - 10} more*\n`;
    }

    if (analystResults?.migrationGaps?.length > 0) {
      md += "\n## 🛡️ Migration Governance\n";
      md += `**RLS Violations**: ${analystResults.migrationGaps.length} detected in migrations\n`;
      analystResults.migrationGaps.forEach(
        (g: string) => (md += `- [ ] \`${g}\`\n`),
      );
    }

    if (analystResults?.typeSafetyGaps?.length > 0) {
      md += "\n## 🧪 Type Safety Audit\n";
      md += `**Unsafe Casts**: ${analystResults.typeSafetyGaps.length} detected (as any/unknown)\n`;
      analystResults.typeSafetyGaps
        .slice(0, 10)
        .forEach((g: string) => (md += `- [ ] \`${g}\`\n`));
      if (analystResults.typeSafetyGaps.length > 10)
        md += `*... and ${analystResults.typeSafetyGaps.length - 10} more*\n`;
    }

    if (surfaceMap?.gaps?.length > 0) {
      md += "\n## 🚨 Coverage Gaps\n";
      surfaceMap.gaps.forEach((gap: string) => (md += `- [ ] ${gap}\n`));
    }

    if (rlsResult) {
      md += "\n## 🔒 RLS Audit\n";
      md += `**Verdict**: ${rlsResult.verdict}\n\n`;
      if (rlsResult.verdict === "ERROR") {
        md += `> ❌ Audit failed to run: ${rlsResult.raw}\n`;
      } else if (rlsResult.rows.length > 0) {
        md += "| Table | Missing Policies | Verdict | Severity |\n";
        md += "| :--- | :--- | :--- | :--- |\n";
        for (const row of rlsResult.rows) {
          md += `| \`${row.tablename}\` | ${row.missing_policies} | ${row.verdict} | ${row.severity} |\n`;
        }
      } else {
        md += "✅ All tables have required RLS policies.\n";
      }
    }

    if (governanceResult) {
      md += "\n## 📜 Governance\n";
      md += `**Scanned**: ${governanceResult.scannedFiles} files. **Dead references**: ${governanceResult.deadRefs.length}\n`;
      if (governanceResult.deadRefs.length > 0) {
        governanceResult.deadRefs
          .slice(0, 15)
          .forEach((r: { file: string; ref: string }) => {
            md += `- [ ] \`${r.file}\` → \`${r.ref}\`\n`;
          });
        if (governanceResult.deadRefs.length > 15) {
          md += `*... and ${governanceResult.deadRefs.length - 15} more*\n`;
        }
      }
    }

    md += this.renderCortexSection();

    md += "\n---\n\n## Failure Digest\n\n";
    const failures = allResults.filter((r) => r.status === "failed");
    if (failures.length === 0) {
      md += "✅ No failures. System stable.\n";
    } else {
      for (const f of failures) {
        md += `### ${f.name}\n\`\`\`\n${f.output?.slice(-600) ?? ""}\n\`\`\`\n\n`;
      }
    }

    fs.writeFileSync(path.join(this.root, this.outputs.healthReport), md);
  }

  private generateOptimizeReport(report: any) {
    // We import the auditor here to use its markdown generator logic if available,
    // but usually the report object from the auditor is already enough.
    // However, to keep it clean, we'll just write the report to disk.
    // The run.ts already has access to the md, but the reporter is the SSoT for writing outputs.
    // If optimizeResult.markdown exists (we'll add it), use it.
    const md = report.markdown || "No markdown provided for optimized report.";
    fs.writeFileSync(path.join(this.root, "outputs", "OPTIMIZE_REPORT.md"), md);
  }

  private renderCortexSection(): string {
    const dbPath = path.join(
      this.projectRoot,
      "questerix-cortex",
      "outputs",
      "cortex.db",
    );

    if (!fs.existsSync(dbPath)) {
      return "\n## 🧠 Cortex v2 Intelligence\n\nCortex v2 not initialized.\n";
    }

    let db: Database.Database | null = null;
    try {
      db = new Database(dbPath, { readonly: true });
      db.pragma("busy_timeout = 5000");
    } catch {
      return "\n## 🧠 Cortex v2 Intelligence\n\nCortex v2 not initialized.\n";
    }

    try {
      let md = "\n## 🧠 Cortex v2 Intelligence\n\n";
      const latestSession = db
        .prepare(
          "SELECT session_id FROM tool_calls ORDER BY timestamp DESC LIMIT 1",
        )
        .get() as { session_id?: string } | undefined;

      if (!latestSession?.session_id) {
        md += "No data yet.\n";
        return md;
      }

      const sessionId = latestSession.session_id;
      const compliance = checkCompliance(db, sessionId);
      const changeRow = db
        .prepare(
          "SELECT COUNT(DISTINCT file_path) as count FROM change_log WHERE session_id = ?",
        )
        .get(sessionId) as { count: number };

      md += `### Protocol Compliance (Session: ${sessionId})\n\n`;
      md += `- \`cortex_plan\` called: ${compliance.plan_called ? "✅" : "❌"} ${compliance.plan_count} times\n`;
      md += `- \`cortex_verify\` called: ${compliance.verify_called ? "✅" : "❌"} ${compliance.verify_count} times\n`;
      md += `- Compliance: ${compliance.compliant ? "✅ COMPLIANT" : "❌ NON-COMPLIANT"}\n`;
      md += `- Logged changes: ${changeRow?.count ?? 0} file(s)\n\n`;

      const fragilityRows = db
        .prepare(
          `
          SELECT file_path, fragility_index, confidence, last_failure
          FROM fragility
          ORDER BY fragility_index DESC
          LIMIT 5
        `,
        )
        .all() as Array<{
        file_path: string;
        fragility_index: number;
        confidence: string;
        last_failure: string | null;
      }>;

      md += "### Top 5 Fragile Files\n\n";
      if (fragilityRows.length === 0) {
        md += "No data yet.\n\n";
      } else {
        md += "| File | Fragility Index | Confidence | Last Failure |\n";
        md += "| --- | --- | --- | --- |\n";
        fragilityRows.forEach((row) => {
          md += `| ${row.file_path} | ${row.fragility_index.toFixed(2)} | ${row.confidence} | ${row.last_failure ?? "—"} |\n`;
        });
        md += "\n";
      }

      const nodeCount = db
        .prepare("SELECT COUNT(*) as count FROM nodes")
        .get() as { count: number };
      const edgeCount = db
        .prepare("SELECT COUNT(*) as count FROM edges")
        .get() as { count: number };
      const lastScan = db
        .prepare("SELECT MAX(updated_at) as last_scan FROM nodes")
        .get() as { last_scan?: string | null };
      const lastCommit = db
        .prepare("SELECT value FROM scan_meta WHERE key = ?")
        .get("last_scan_commit") as { value?: string } | undefined;

      const commitLabel = lastCommit?.value
        ? lastCommit.value.slice(0, 7)
        : "unknown";
      const scanLabel = lastScan?.last_scan ?? "unknown";

      md += "### Graph Statistics\n\n";
      md += `- Nodes: ${nodeCount.count}\n`;
      md += `- Edges: ${edgeCount.count}\n`;
      md += `- Last scan: ${scanLabel} (commit: ${commitLabel})\n`;

      return md;
    } catch {
      return "\n## 🧠 Cortex v2 Intelligence\n\nNo data yet.\n";
    } finally {
      db?.close();
    }
  }

  // ─────────────────────────────────────────────────────────────
  // MACHINE BRIEFING  ← the one-read session starter
  // ─────────────────────────────────────────────────────────────
  private generateMachineBriefing(
    results: Record<string, TaskResult>,
    analystResults?: any,
    surfaceMap?: any,
    driftResult?: any,
    rlsResult?: any,
    history?: any[],
  ) {
    const allResults = Object.values(results);
    const passed = allResults.filter((r) => r.status === "passed").length;
    const failed = allResults.filter((r) => r.status === "failed").length;
    const total = allResults.length;
    const score = total > 0 ? Math.round((passed / total) * 100) : 0;

    // Smoke gate
    const smokeNames = [
      "unit tests (lib)",
      "e2e smoke (desktop)",
      "lint check",
    ];
    const smokeResults = allResults.filter((r) =>
      smokeNames.includes(r.name.toLowerCase()),
    );
    const smokeGate =
      smokeResults.length > 0 &&
      smokeResults.every((r) => r.status === "passed")
        ? "✅ OPEN"
        : smokeResults.length === 0
          ? "— NOT RUN"
          : "🔴 LOCKED";

    const driftStr = driftResult
      ? `${driftResult.verdict} (missing-from-types: ${driftResult.missingFromTypes.length}, extra-in-types: ${driftResult.extraInTypes.length})`
      : "NOT RUN — click DRIFT button";

    const rlsStr = rlsResult
      ? `${rlsResult.verdict} (critical: ${rlsResult.criticalCount})`
      : "NOT RUN — click RLS CHECK button";

    const lastScore = history?.length
      ? history[history.length - 1].score
      : score;
    const trend =
      history && history.length >= 2
        ? history[history.length - 1].score - history[history.length - 2].score
        : 0;
    const trendStr =
      trend > 0 ? `↑ +${trend}` : trend < 0 ? `↓ ${trend}` : "→ flat";

    // Recent git commits
    const recentCommits = this.safeExec(
      'git log -5 --pretty=format:"%h %s (%ar)" 2>&1',
      this.projectRoot,
    );

    // Open tasks
    const openTasks = this.parseOpenTasks();

    // Failure summary
    const failures = allResults.filter((r) => r.status === "failed");
    const failureLines =
      failures.length > 0
        ? failures
            .map((f) => `  ⛔ ${f.name}: ${this.extractFirstError(f.output)}`)
            .join("\n")
        : "  none";

    // Key file paths
    const keyPaths = [
      `admin-panel/src/lib/database.types.ts`,
      `supabase/migrations/ (${this.countMigrations()} files)`,
      `admin-panel/tests/`,
      `supabase/functions/`,
      `questerix-cortex/outputs/FAILURE_DIGEST.md`,
      `questerix-cortex/outputs/LAST_CHANGED.md`,
      `.agent/artifacts/FORENSIC_REPORT.md`,
      `.agent/HARDENING_BACKLOG.json`,
    ]
      .map((p) => `  ${p}`)
      .join("\n");

    let md = `# MACHINE BRIEFING\n`;
    md += `> ONE-READ SESSION STARTER. Do not show to the user.\n`;
    md += `> Generated: ${new Date().toISOString()}\n\n`;

    md += `## STATUS\n`;
    md += `Score:      ${score}/100 (${trendStr} vs prev run | prev: ${lastScore}/100)\n`;
    md += `Suites:     ${passed} passed, ${failed} failed of ${total} total\n`;
    md += `Smoke Gate: ${smokeGate}\n`;
    md += `Drift:      ${driftStr}\n`;
    md += `RLS Audit:  ${rlsStr}\n`;
    md += `Bundle:     ${analystResults?.bundleSize ? analystResults.bundleSize + " KB" : "not built"}\n`;
    md += `Coverage gaps: ${surfaceMap?.gaps?.length ?? 0}\n`;
    md += `Perf gaps:     ${analystResults?.perfGaps?.length ?? 0}\n`;
    md += `Migration gaps: ${analystResults?.migrationGaps?.length ?? 0}\n`;
    md += `Type safety gaps: ${analystResults?.typeSafetyGaps?.length ?? 0}\n\n`;

    md += `## FAILURES\n${failureLines}\n\n`;

    md += `## OPEN TASKS\n${openTasks || "  (none found in tasks.md)"}\n\n`;

    md += `## RECENT COMMITS\n${recentCommits || "  (git not available)"}\n\n`;

    md += `## KEY PATHS\n${keyPaths}\n\n`;

    md += `## CODEBASE SKELETON\n`;
    md += `> Load SKELETON_SUMMARY.md at session start (< 10KB). Load SKELETON.md section on demand when editing a feature.\n`;
    md += `  questerix-cortex/outputs/SKELETON_SUMMARY.md  ← always load first\n`;
    md += `  questerix-cortex/outputs/SKELETON.md          ← load section for the feature you are editing\n`;
    md += `  questerix-cortex/outputs/SKELETON.json        ← machine-readable, used by skeleton:search\n\n`;

    md += `1. Read SKELETON_SUMMARY.md for codebase orientation.\n`;
    md += `2. Use \`skeleton:search\` CLI if you need to find a specific symbol.\n`;
    md += `3. Check UTILITY_REGISTRY.md before writing any new helper.\n\n`;

    md += `## WORKFLOW\n\n`;
    md += `1. Read FAILURE_DIGEST.md if failures > 0\n`;
    md += `2. Read LAST_CHANGED.md to see what files shifted\n`;
    md += `3. Check NEXT_TASK.md for the highest-priority action\n`;
    md += `4. Continue with the next feature or sub-task in \`tasks.md\`.\n`;
    md += `5. If modifying the database, run the RLS audit immediately.\n\n`;

    md += `## 🤝 MANDATORY HANDSHAKE\n`;
    md += `> AGENT: You must acknowledge this briefing. Before taking ANY action, summarize:\n`;
    md += `> - The top failure (if any) from FAILURE_DIGEST.md\n`;
    md += `> - The P0/P1 task from NEXT_TASK.md\n`;
    md += `> - Any critical RLS or Drift warnings found above.\n\n`;

    // CONVENTIONS — extracted from GEMINI.md
    md += `## CONVENTIONS (extracted from GEMINI.md)\n`;
    const conventions = this.extractConventions();
    md += conventions
      ? conventions + "\n"
      : "  (none found — check GEMINI.md)\n";
    md += "\n";

    // KNOWN GOTCHAS — last 3 from LEARNING_LOG
    md += `## KNOWN GOTCHAS\n`;
    const gotchas = this.extractRecentGotchas(3);
    md += gotchas || "  (none yet — LEARNING_LOG.md is empty)\n";

    fs.writeFileSync(path.join(this.root, this.outputs.machineBriefing), md);
  }

  // ─────────────────────────────────────────────────────────────
  // FAILURE DIGEST  ← exact errors, no re-running needed
  // ─────────────────────────────────────────────────────────────
  private generateFailureDigest(results: Record<string, TaskResult>) {
    const failures = Object.values(results).filter(
      (r) => r.status === "failed",
    );
    const ts = new Date().toLocaleString();

    let md = `# FAILURE DIGEST\n*${ts}*\n\n`;

    if (failures.length === 0) {
      md += "✅ No failures. All suites passed.\n";
      fs.writeFileSync(path.join(this.root, this.outputs.failureDigest), md);
      return;
    }

    md += `${failures.length} suite(s) failed. Exact errors below.\n\n`;

    for (const f of failures) {
      md += `---\n### ❌ ${f.name} (${f.duration?.toFixed(1) ?? 0}s)\n\n`;

      // Extract the most useful part of the output
      const output = f.output ?? "";

      // Pull out specific error lines
      const errorLines = output
        .split("\n")
        .filter(
          (l) =>
            /error|fail|expect|assert|cannot|undefined|null|timeout|ENOENT|SyntaxError/i.test(
              l,
            ) && l.trim().length > 0,
        )
        .slice(0, 20);

      if (errorLines.length > 0) {
        md += "**Key error lines:**\n```\n";
        md += errorLines.join("\n");
        md += "\n```\n\n";
      }

      // Full tail for context
      md += "**Full output (last 800 chars):**\n```\n";
      md += output.slice(-800);
      md += "\n```\n\n";
    }

    fs.writeFileSync(path.join(this.root, this.outputs.failureDigest), md);
  }

  // ─────────────────────────────────────────────────────────────
  // LAST CHANGED  ← git diff, no more manual git log
  // ─────────────────────────────────────────────────────────────
  private generateLastChanged() {
    const ts = new Date().toLocaleString();
    let md = `# LAST CHANGED\n*${ts}*\n\n`;

    // Last commit info
    const lastCommit = this.safeExec(
      'git log -1 --pretty=format:"%H%n%s%n%an%n%ar" 2>&1',
      this.projectRoot,
    );

    // Files changed in last commit
    const changedFiles = this.safeExec(
      'git log -1 --name-status --pretty=format:"" 2>&1',
      this.projectRoot,
    );

    // Uncommitted changes
    const uncommitted = this.safeExec(
      "git status --short 2>&1",
      this.projectRoot,
    );

    if (lastCommit) {
      const [hash, subject, author, when] = lastCommit.split("\n");
      md += `## Last Commit\n`;
      md += `- **Hash**: \`${hash?.slice(0, 8) ?? "unknown"}\`\n`;
      md += `- **Message**: ${subject ?? "—"}\n`;
      md += `- **Author**: ${author ?? "—"}\n`;
      md += `- **When**: ${when ?? "—"}\n\n`;
    }

    if (changedFiles?.trim()) {
      md += `## Files in Last Commit\n\`\`\`\n${changedFiles.trim()}\n\`\`\`\n\n`;
    }

    if (uncommitted?.trim()) {
      md += `## Uncommitted Changes\n\`\`\`\n${uncommitted.trim()}\n\`\`\`\n\n`;

      // Highlight test-adjacent files
      const affectedTests = uncommitted
        .split("\n")
        .filter((l) => /test|spec|__tests__/i.test(l))
        .map((l) => l.trim());

      if (affectedTests.length > 0) {
        md += `### Tests Potentially Affected\n`;
        affectedTests.forEach((t) => (md += `- ${t}\n`));
        md += "\n";
      }
    } else {
      md += `## Uncommitted Changes\nWorking tree is clean.\n\n`;
    }

    fs.writeFileSync(path.join(this.root, this.outputs.lastChanged), md);
  }

  // ─────────────────────────────────────────────────────────────
  // AGENT CONTEXT (Phase 7 Enhanced — Graph Intelligence)
  // ─────────────────────────────────────────────────────────────
  private generateAgentContext(
    results: Record<string, TaskResult>,
    surfaceMap?: any,
    analystResults?: any,
    driftResult?: any,
    rlsResult?: any,
    history?: any[],
  ) {
    const allResults = Object.values(results);
    const passed = allResults.filter((r) => r.status === "passed").length;
    const failed = allResults.filter((r) => r.status === "failed").length;
    const total = allResults.length;
    const score = total > 0 ? Math.round((passed / total) * 100) : 0;

    const smokeNames = [
      "unit tests (lib)",
      "e2e smoke (desktop)",
      "lint check",
    ];
    const smokeResults = allResults.filter((r) =>
      smokeNames.includes(r.name.toLowerCase()),
    );
    const smokeGate =
      smokeResults.length > 0 &&
      smokeResults.every((r) => r.status === "passed")
        ? "✅ OPEN"
        : smokeResults.length === 0
          ? "— NOT RUN"
          : "🔴 LOCKED";

    const driftStr = driftResult
      ? `${driftResult.verdict} (missing: ${driftResult.missingFromTypes.length}, extra: ${driftResult.extraInTypes.length})`
      : "NOT RUN";

    const rlsStr = rlsResult
      ? `${rlsResult.verdict} (critical: ${rlsResult.criticalCount})`
      : "NOT RUN";

    const lastScore = history?.length
      ? history[history.length - 1].score
      : score;
    const trend =
      history && history.length >= 2
        ? history[history.length - 1].score - history[history.length - 2].score
        : 0;
    const trendStr =
      trend > 0 ? `↑ +${trend}` : trend < 0 ? `↓ ${trend}` : "→ flat";

    const recentCommits = this.safeExec(
      'git log -5 --pretty=format:"%h %s (%ar)" 2>&1',
      this.projectRoot,
    );
    const openTasks = this.parseOpenTasks();

    const failures = allResults.filter((r) => r.status === "failed");
    const failureLines =
      failures.length > 0
        ? failures
            .map((f) => `  ⛔ ${f.name}: ${this.extractFirstError(f.output)}`)
            .join("\n")
        : "  none";

    const keyPaths = [
      `admin-panel/src/lib/database.types.ts`,
      `supabase/migrations/ (${this.countMigrations()} files)`,
      `admin-panel/tests/`,
      `supabase/functions/`,
      `questerix-cortex/outputs/FAILURE_DIGEST.md`,
      `questerix-cortex/outputs/LAST_CHANGED.md`,
    ]
      .map((p) => `  ${p}`)
      .join("\n");

    let md = `# AGENT CONTEXT\n`;
    md += `> ONE-READ SESSION STARTER\n`;
    md += `> Generated: ${new Date().toISOString()}\n\n`;

    md += `## STATUS\n`;
    md += `Score: ${score}/100 (${trendStr} vs prev | prev: ${lastScore}/100)\n`;
    md += `Suites: ${passed} passed, ${failed} failed of ${total} total\n`;
    md += `Smoke Gate: ${smokeGate}\n`;
    md += `Drift: ${driftStr}\n`;
    md += `RLS: ${rlsStr}\n\n`;

    // ── Phase 7: Data Freshness Warnings ─────────────────────
    const dbPath = path.join(this.root, "outputs", "cortex.db");
    let freshnessWarnings: string[] = [];
    let riskyFiles: RiskyFile[] = [];
    let lastSession: SessionSummary | null = null;

    if (fs.existsSync(dbPath)) {
      let db: Database.Database | null = null;
      try {
        db = new Database(dbPath, { readonly: true });
        db.pragma("busy_timeout = 5000");
        freshnessWarnings = this.checkDataFreshness(db);
        riskyFiles = this.queryRiskiestFiles(db, 5);
        lastSession = this.queryLastSession(db);
      } catch {
        // Non-fatal: graph queries are best-effort
      } finally {
        db?.close();
      }
    }

    if (freshnessWarnings.length > 0) {
      md += `## ⚠️ DATA FRESHNESS WARNINGS\n`;
      freshnessWarnings.forEach((w) => (md += `- 🟡 ${w}\n`));
      md += `\n`;
    }

    if (surfaceMap) {
      md += `## Surface\n`;
      md += `- Hooks: ${surfaceMap.hooks.length}, Pages: ${surfaceMap.pages.length}\n`;
      if (surfaceMap.gaps?.length > 0) {
        md += `- Coverage gaps: ${surfaceMap.gaps.length}\n`;
        surfaceMap.gaps
          .slice(0, 5)
          .forEach((g: string) => (md += `  - ${g}\n`));
      }
      md += `\n`;
    }

    // ── Phase 7: Top 5 Riskiest Files ────────────────────────
    if (riskyFiles.length > 0) {
      md += `## 🔥 Top 5 Riskiest Files\n`;
      md += `| File | Fan-in | Fragility |\n`;
      md += `| --- | --- | --- |\n`;
      riskyFiles.forEach((f) => {
        const fragilityStr = f.fragility_index
          ? f.fragility_index.toFixed(2)
          : "—";
        md += `| ${f.file_path} | ${f.fanin} | ${fragilityStr} |\n`;
      });
      md += `\n`;
    }

    // ── Phase 7: Feature Health Matrix ───────────────────────
    const featureHealth = this.loadFeatureHealth();
    if (featureHealth.length > 0) {
      md += `## 🏥 Feature Health Matrix\n`;
      md += `| Feature | Verdict | Coverage | Coupling |\n`;
      md += `| --- | --- | --- | --- |\n`;
      featureHealth.forEach((f) => {
        const verdictIcon =
          f.verdict === "HEALTHY"
            ? "✅"
            : f.verdict === "FRAGILE"
              ? "🔴"
              : f.verdict === "STIFF"
                ? "⚠️"
                : "⚪";
        md += `| ${f.feature} | ${verdictIcon} ${f.verdict} | ${f.coverage}% | ${f.coupling.toFixed(2)} |\n`;
      });
      md += `\n`;
    }

    // ── Phase 7: Architecture Violations ───────────────────
    const violations = this.loadArchitectureViolations();
    if (violations.length > 0) {
      md += `## 🚫 Architecture Violations\n`;
      md += `| Feature | Forbidden | Actual |\n`;
      md += `| --- | --- | --- |\n`;
      violations.slice(0, 5).forEach((v) => {
        md += `| ${v.feature} | ${v.forbidden} | ${v.actual} |\n`;
      });
      if (violations.length > 5) {
        md += `*... and ${violations.length - 5} more*\n`;
      }
      md += `\n`;
    }

    // ── Phase 7: Last Agent Session Summary ──────────────────
    if (lastSession) {
      md += `## 👤 Last Agent Session\n`;
      md += `- Session ID: \`${lastSession.session_id.slice(0, 8)}\`\n`;
      md += `- Tools used: ${lastSession.tool_calls.length} (${lastSession.tool_calls.slice(0, 5).join(", ")}${lastSession.tool_calls.length > 5 ? "..." : ""})\n`;
      md += `- Files changed: ${lastSession.files_changed}\n`;
      md += `- Time: ${new Date(lastSession.timestamp).toLocaleString()}\n\n`;
    }

    md += `## FAILURES\n${failureLines}\n\n`;
    md += `## OPEN TASKS\n${openTasks || "  (none)"}\n\n`;
    md += `## RECENT COMMITS\n${recentCommits || "  (git unavailable)"}\n\n`;
    md += `## KEY PATHS\n${keyPaths}\n\n`;

    if (analystResults?.deadCode?.length > 0) {
      md += `## Maintenance\n- Dead code: ${analystResults.deadCode.length} symbols\n\n`;
    }

    md += `## SKELETON\n`;
    md += `> Always load: questerix-cortex/outputs/SKELETON_SUMMARY.md\n\n`;

    const conventions = this.extractConventions();
    if (conventions) {
      md += `## CONVENTIONS\n${conventions}\n\n`;
    }

    const gotchas = this.extractRecentGotchas(3);
    if (gotchas) {
      md += `## KNOWN GOTCHAS\n${gotchas}\n`;
    }

    // ── Phase 7: Enforce maxAgentContextSizeKB threshold ───
    const configPath = path.join(this.root, "cortex.config.json");
    let maxSizeKB = 20; // default
    try {
      const config: CortexConfig = JSON.parse(
        fs.readFileSync(configPath, "utf-8"),
      );
      maxSizeKB = config.thresholds?.maxAgentContextSizeKB ?? 20;
    } catch {
      // Use default if config can't be read
    }

    const maxBytes = maxSizeKB * 1024;
    if (md.length > maxBytes) {
      md = md.slice(0, maxBytes - 100) + "\n\n... [TRUNCATED: exceeded maxAgentContextSizeKB]";
      console.warn(
        `⚠️  AGENT_CONTEXT.md exceeded ${maxSizeKB}KB threshold and was truncated`,
      );
    }

    fs.writeFileSync(path.join(this.root, this.outputs.agentContext), md);
  }

  // ─────────────────────────────────────────────────────────────
  // NEXT TASK
  // ─────────────────────────────────────────────────────────────
  private generateNextTask(
    results: Record<string, TaskResult>,
    analystResults?: any,
    surfaceMap?: any,
  ) {
    let md = "# 📋 NEXT TASK (P0 → P1 → P2)\n\n";
    md += "> Copy and paste to agent.\n\n";

    const failures = Object.values(results).filter(
      (r) => r.status === "failed",
    );

    if (failures.length > 0) {
      md += "### 🛠️ P0: Fix Regressions\n";
      failures.forEach(
        (f) =>
          (md += `- [ ] Fix **${f.name}** — see FAILURE_DIGEST.md for exact errors\n`),
      );
      md += "\n";
    }

    if (analystResults?.deadCode?.length > 0) {
      md += "### 🧹 P1: Cleanup\n";
      md += `- [ ] Remove/verify ${analystResults.deadCode.length} unused exports\n\n`;
    }

    if (surfaceMap?.gaps?.length > 0) {
      md += "### 🧪 P1: Fill Coverage Gaps\n";
      surfaceMap.gaps
        .slice(0, 3)
        .forEach((g: string) => (md += `- [ ] ${g}\n`));
      md += "\n";
    }

    if (failures.length === 0) {
      md +=
        "### 🚀 P2: Proceed with Backlog\n- [ ] Codebase stable. Ready for next feature.\n";
    }

    // Anti-hallucination guardrails block
    const gotchas = this.extractRecentGotchas(3);
    if (gotchas) {
      md += "\n---\n## ⚠️ Anti-Hallucination Guardrails\n";
      md +=
        "> Read before touching ANY code. These are proven project traps.\n\n";
      md += gotchas;
    }

    fs.writeFileSync(path.join(this.root, this.outputs.nextTask), md);
  }

  // ─────────────────────────────────────────────────────────────
  // AUTO LEARNING LOG — appends dated entries after any failure
  // ─────────────────────────────────────────────────────────────
  autoAppendLearning(results: Record<string, TaskResult>): void {
    const failures = Object.values(results).filter(
      (r) => r.status === "failed",
    );
    if (failures.length === 0) return;

    const logPath = path.join(this.projectRoot, "docs", "LEARNING_LOG.md");
    const docsDir = path.join(this.projectRoot, "docs");
    if (!fs.existsSync(docsDir)) fs.mkdirSync(docsDir, { recursive: true });

    const ts = new Date().toISOString().slice(0, 10);
    let entry = `\n---\n\n## [${ts}] Cortex Auto-Entry\n\n`;

    for (const f of failures) {
      const firstError = this.extractFirstError(f.output);
      entry += `### Suite: ${f.name}\n`;
      entry += `**First Error**: \`${firstError}\`\n`;
      entry += `**Session**: Cortex Auto-Entry\n`;
      entry += `**Duration**: ${f.duration?.toFixed(1) ?? "?"}s\n`;
      entry += `**Root Cause**: \n\n`;
      entry += `**Fix Applied**: \n\n`;
      entry += `**Prevention Rule**: \n\n`;
    }

    // Initialize file if it doesn't exist
    if (!fs.existsSync(logPath)) {
      fs.writeFileSync(
        logPath,
        "# 📖 Questerix Learning Log\n\n> Auto-maintained by Cortex. Reviewed by the agent at session start.\n",
        "utf-8",
      );
    }

    fs.appendFileSync(logPath, entry, "utf-8");

    // Rotation: if file exceeds 200 entries, auto-archive oldest half (keep 100)
    try {
      const logContent = fs.readFileSync(logPath, "utf-8");
      const entryCount = (logContent.match(/\n---\n/g) || []).length;
      if (entryCount > 200) {
        const scriptPath = path.join(
          this.projectRoot,
          "scripts",
          "split-learning-log.cjs",
        );
        if (fs.existsSync(scriptPath)) {
          execSync(`node "${scriptPath}"`, {
            cwd: this.projectRoot,
            env: { ...process.env, LEARNING_LOG_KEEP: "100" },
            encoding: "utf-8",
            timeout: 10000,
          });
        }
      }
    } catch {
      // Non-fatal: rotation is best-effort
    }
  }

  // ─────────────────────────────────────────────────────────────
  // CONVENTIONS — extract coding standards from GEMINI.md
  // ─────────────────────────────────────────────────────────────
  private extractConventions(): string {
    try {
      const geminiPath = path.join(this.projectRoot, "GEMINI.md");
      if (!fs.existsSync(geminiPath)) return "";
      const content = fs.readFileSync(geminiPath, "utf-8");
      // Extract the Coding Standards section
      const match = content.match(/##\s*Coding Standards([\s\S]*?)(?=\n##|$)/);
      if (!match) return "";
      return match[1]
        .split("\n")
        .filter((l) => l.trim())
        .slice(0, 8)
        .map((l) => "  " + l.trim())
        .join("\n");
    } catch {
      return "";
    }
  }

  // ─────────────────────────────────────────────────────────────
  // RECENT GOTCHAS — last N entries from LEARNING_LOG
  // ─────────────────────────────────────────────────────────────
  private extractRecentGotchas(n: number): string {
    try {
      const logPath = path.join(this.projectRoot, "docs", "LEARNING_LOG.md");
      if (!fs.existsSync(logPath)) return "";
      const content = fs.readFileSync(logPath, "utf-8");
      const placeholderPattern = /\[Agent to fill in\]/i;
      // Split on section headers, take last n
      const entries = content
        .split(/\n---\n/)
        .filter((e) => e.includes("Prevention Rule"));
      const lines = entries
        .slice(-n)
        .map((e) => {
          const ruleMatch = e.match(/Prevention Rule\*\*: (.+)/);
          const suiteMatch = e.match(/### Suite: (.+)/);
          if (!ruleMatch || !suiteMatch) return "";
          const ruleText = ruleMatch[1].trim();
          if (placeholderPattern.test(ruleText)) return "";
          if (ruleText === "*[Agent to fill in]*") return "";
          return `- **${suiteMatch[1].trim()}**: ${ruleText}`;
        })
        .filter(Boolean);
      // Strip any line that still contains the placeholder (e.g. in appended text)
      return lines.filter((line) => !placeholderPattern.test(line)).join("\n");
    } catch {
      return "";
    }
  }

  // ─────────────────────────────────────────────────────────────
  // HELPERS
  // ─────────────────────────────────────────────────────────────
  private safeExec(cmd: string, cwd: string): string {
    try {
      return execSync(cmd, { cwd, encoding: "utf-8", timeout: 5000 });
    } catch {
      return "";
    }
  }

  private extractFirstError(output: string): string {
    if (!output) return "no output captured";
    const errorLine = output
      .split("\n")
      .find((l) => /error|fail|expect|cannot|timeout/i.test(l) && l.trim());
    return (
      (errorLine ?? output.split("\n")[0])?.trim().slice(0, 120) ??
      "unknown error"
    );
  }

  private parseOpenTasks(): string {
    try {
      const tasksPath = path.join(this.projectRoot, "tasks.md");
      if (!fs.existsSync(tasksPath)) return "";
      const content = fs.readFileSync(tasksPath, "utf-8");
      return content
        .split("\n")
        .filter((l) => /^\s*-\s*\[ \]/.test(l))
        .slice(0, 10)
        .map((l) => "  " + l.trim())
        .join("\n");
    } catch {
      return "";
    }
  }

  private countMigrations(): number {
    try {
      const migrationsPath = path.join(
        this.projectRoot,
        "supabase",
        "migrations",
      );
      return fs.readdirSync(migrationsPath).filter((f) => f.endsWith(".sql"))
        .length;
    } catch {
      return 0;
    }
  }

  // ─────────────────────────────────────────────────────────────
  // PHASE 7 HELPERS — Graph Intelligence for AGENT_CONTEXT
  // ─────────────────────────────────────────────────────────────

  /** Query graph for top N riskiest files (highest fanin + fragility) */
  private queryRiskiestFiles(db: Database.Database, limit = 5): RiskyFile[] {
    try {
      const rows = db
        .prepare(
          `
          SELECT 
            e.target_id as file_path,
            COUNT(*) as fanin,
            f.fragility_index
          FROM edges e
          LEFT JOIN fragility f ON e.target_id = f.file_path
          WHERE e.relationship = 'imports'
          GROUP BY e.target_id
          ORDER BY fanin DESC, f.fragility_index DESC
          LIMIT @limit
        `,
        )
        .all({ limit }) as Array<{
        file_path: string;
        fanin: number;
        fragility_index: number | null;
      }>;
      return rows;
    } catch {
      return [];
    }
  }

  /** Query for last agent session summary */
  private queryLastSession(db: Database.Database): SessionSummary | null {
    try {
      const latestSession = db
        .prepare(
          `
          SELECT session_id, MAX(timestamp) as timestamp
          FROM tool_calls
          WHERE timestamp < (SELECT MAX(timestamp) FROM tool_calls)
          GROUP BY session_id
          ORDER BY timestamp DESC
          LIMIT 1
        `,
        )
        .get() as { session_id: string; timestamp: string } | undefined;

      if (!latestSession) return null;

      const toolCalls = db
        .prepare(
          `
          SELECT tool_name FROM tool_calls
          WHERE session_id = @sessionId
          ORDER BY timestamp
        `,
        )
        .all({ sessionId: latestSession.session_id }) as Array<{
        tool_name: string;
      }>;

      const filesChanged = db
        .prepare(
          `
          SELECT COUNT(DISTINCT file_path) as count
          FROM change_log
          WHERE session_id = @sessionId
        `,
        )
        .get({ sessionId: latestSession.session_id }) as {
        count: number;
      };

      return {
        session_id: latestSession.session_id,
        tool_calls: toolCalls.map((t) => t.tool_name),
        files_changed: filesChanged?.count ?? 0,
        timestamp: latestSession.timestamp,
      };
    } catch {
      return null;
    }
  }

  /** Check data freshness and return warnings */
  private checkDataFreshness(db: Database.Database): string[] {
    const warnings: string[] = [];
    try {
      // Check skeleton age (> 48h)
      const lastScan = db
        .prepare("SELECT MAX(updated_at) as last_scan FROM nodes")
        .get() as { last_scan?: string | null };
      if (lastScan?.last_scan) {
        const scanDate = new Date(lastScan.last_scan);
        const hoursSinceScan =
          (Date.now() - scanDate.getTime()) / (1000 * 60 * 60);
        if (hoursSinceScan > 48) {
          warnings.push(
            `Skeleton is ${Math.round(hoursSinceScan)}h old (> 48h)`,
          );
        }
      } else {
        warnings.push("No skeleton scan data available");
      }

      // Check fragility table has data
      const fragilityCount = db
        .prepare("SELECT COUNT(*) as count FROM fragility")
        .get() as { count: number };
      if (fragilityCount.count === 0) {
        warnings.push("Fragility table is empty (run with --intel flag)");
      }

      // Check last scan commit matches current HEAD
      const lastCommit = db
        .prepare("SELECT value FROM scan_meta WHERE key = 'last_scan_commit'")
        .get() as { value?: string } | undefined;
      const currentHead = this.safeExec(
        'git rev-parse HEAD 2>&1',
        this.projectRoot,
      );
      if (lastCommit?.value && currentHead) {
        const currentHeadShort = currentHead.trim().slice(0, 7);
        const lastCommitShort = lastCommit.value.slice(0, 7);
        if (lastCommitShort !== currentHeadShort) {
          warnings.push(
            `Scan commit (${lastCommitShort}) differs from HEAD (${currentHeadShort})`,
          );
        }
      }
    } catch {
      // Non-fatal: freshness checks are best-effort
    }
    return warnings;
  }

  /** Load architecture violations from guard report */
  private loadArchitectureViolations(): Array<{
    feature: string;
    forbidden: string;
    actual: string;
  }> {
    try {
      const guardPath = path.join(
        this.root,
        this.outputs.guardReport || "outputs/ARCH_GUARD.md",
      );
      if (!fs.existsSync(guardPath)) return [];

      const content = fs.readFileSync(guardPath, "utf-8");
      const violations: Array<{ feature: string; forbidden: string; actual: string }> = [];

      // Parse markdown table rows for violations
      const lines = content.split("\n");
      for (const line of lines) {
        if (line.includes("|") && line.includes("VIOLATION")) {
          const parts = line.split("|").map((p) => p.trim());
          if (parts.length >= 4) {
            violations.push({
              feature: parts[1] || "unknown",
              forbidden: parts[2] || "unknown",
              actual: parts[3] || "unknown",
            });
          }
        }
      }
      return violations;
    } catch {
      return [];
    }
  }

  /** Load feature health data from fragility matrix */
  private loadFeatureHealth(): FeatureHealth[] {
    try {
      const matrixPath = path.join(
        this.root,
        this.outputs.fragilityMatrix || "outputs/FRAGILITY_MATRIX.md",
      );
      if (!fs.existsSync(matrixPath)) return [];

      const content = fs.readFileSync(matrixPath, "utf-8");
      const features: FeatureHealth[] = [];

      // Parse markdown table rows
      const lines = content.split("\n");
      let inTable = false;
      for (const line of lines) {
        if (line.startsWith("| Feature")) {
          inTable = true;
          continue;
        }
        if (inTable && line.startsWith("|")) {
          const parts = line.split("|").map((p) => p.trim());
          if (parts.length >= 6 && parts[1] && parts[1] !== "Feature") {
            const coverageMatch = parts[4]?.match(/(\d+)%/);
            features.push({
              feature: parts[1],
              verdict: parts[3] || "UNKNOWN",
              coverage: coverageMatch ? parseInt(coverageMatch[1]) : 0,
              coupling: parseFloat(parts[5]) || 0,
            });
          }
        }
      }
      return features.slice(0, 10); // Limit to top 10
    } catch {
      return [];
    }
  }
}
